name: Android CI
on:
  pull_request:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
      - name: Set up Gradle 8.11.1
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.11.1
      - name: Lint & Unit tests
        run: gradle :app:lint :app:testDebugUnitTest --no-daemon --stacktrace
      - name: Build debug APK
        run: gradle :app:assembleDebug --no-daemon --stacktrace
      - name: Prepare artifact
        run: |
          mkdir -p dist
          cp app/build/outputs/apk/debug/*.apk dist/
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: paisasplit-debug-apk
          path: dist/*.apk
      - name: Publish APK to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: debug-${{ github.run_id }}
          name: "SplitPaisa Debug #${{ github.run_number }}"
          prerelease: true
          files: dist/*.apk
