name: Android CI
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - uses: gradle/actions/setup-gradle@v3
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
      - name: Lint & Unit tests
        run: gradle :app:lint :app:testDebugUnitTest
      - name: Build debug APK
        run: gradle :app:assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: paisasplit-debug-apk
          path: app/build/outputs/**/*.apk
